language: generic

os:
  - linux

dist:
  - bionic

addons:
  apt:
    packages:
    - qemu
  snaps:
    - name: go
      confinement: classic

services:
  - docker

env:
  - GO111MODULE=on

before_script:
  - go get -u code.dumpstack.io/tools/out-of-tree
  - out-of-tree bootstrap
  - out-of-tree kernel autogen --max=8
  - sudo ln -s $HOME/.out-of-tree /root/

script:
  - sudo $(which out-of-tree) pew --max=8
